[workspace]
resolver = "2"

members = [ 
    "mbf-adb-killer",
    "mbf-agent",
    "mbf-res-man",
    "mbf-zip",
    "mbf-axml"
]

[profile.dev.package."*"]
opt-level = 3

[profile.release]
strip = true
